server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: transection_service   # ? Important

  flyway:
    enabled: true
    locations: classpath:db/migration/user_service
    schemas: user_service   # ? Flyway will track migrations per schema
