version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: postgres_cbp
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5433:5433"
